In [1]:
import numpy as np

In [12]:
i16 = np.dtype(np.int16)
print(i16)

int16


In [13]:
lst = np.linspace(0,115,28).reshape(4,7)
lst

array([[  0.        ,   4.25925926,   8.51851852,  12.77777778,
         17.03703704,  21.2962963 ,  25.55555556],
       [ 29.81481481,  34.07407407,  38.33333333,  42.59259259,
         46.85185185,  51.11111111,  55.37037037],
       [ 59.62962963,  63.88888889,  68.14814815,  72.40740741,
         76.66666667,  80.92592593,  85.18518519],
       [ 89.44444444,  93.7037037 ,  97.96296296, 102.22222222,
        106.48148148, 110.74074074, 115.        ]])

In [14]:
A = np.array(lst, dtype = i16)
print(A)

[[  0   4   8  12  17  21  25]
 [ 29  34  38  42  46  51  55]
 [ 59  63  68  72  76  80  85]
 [ 89  93  97 102 106 110 115]]


**STRUCTURE ARRAY**

In [18]:
import numpy as np

dt = np.dtype([('density', np.int32)])

x = np.array([(393,), (337,), (256,)], dtype = dt)
print(x)
y = np.array([393, 337, 256], dtype = dt)
print(y)

[(393,) (337,) (256,)]
[(393,) (337,) (256,)]


In [19]:
print(x['density'])

[393 337 256]


In [29]:
import numpy as np

dt = np.dtype([('density', 'i4')])

x = np.array([(393,), (337,), (256,)], dtype = dt)
print(x)

[(393,) (337,) (256,)]


In [58]:
import numpy as np

dt = np.dtype([('Country','S20'),
               ('Density', 'i4'),
               ('Area','i4'),('Population','i4')])

population_table = np.array([
    ('Netherlands', 393, 41526, 16928800),
    ('Belguim', 337, 30510, 11007020),
    ('United Kingdom', 256, 243610, 62262000),
    ('Germany', 233, 357021, 81799600),
    ('Liechtensien', 205, 160, 32842),
    ('Italy', 192, 301230, 59715625),
    ('Switzerland', 177, 41290, 7301994),
    ('Luxembourg', 173, 2586, 512000),
    ('France', 111, 547030, 63601002),
    ('Austria', 97, 83858, 8169929),
    ('Greece', 81, 131940, 11606813),
    ('Ireland', 65, 70280, 4581269),
    ('Sweden', 20, 449964, 9515744),
    ('Finland', 16, 338424,5140233),
    ('Norway', 13, 385252, 5033675)], dtype = dt)
print(population_table[:4])

[(b'Netherlands', 393,  41526, 16928800)
 (b'Belguim', 337,  30510, 11007020)
 (b'United Kingdom', 256, 243610, 62262000)
 (b'Germany', 233, 357021, 81799600)]


In [59]:
print(population_table['Density'])
print(population_table['Country'])
print(population_table['Area'][2:5])

[393 337 256 233 205 192 177 173 111  97  81  65  20  16  13]
[b'Netherlands' b'Belguim' b'United Kingdom' b'Germany' b'Liechtensien'
 b'Italy' b'Switzerland' b'Luxembourg' b'France' b'Austria' b'Greece'
 b'Ireland' b'Sweden' b'Finland' b'Norway']
[243610 357021    160]


**INPUT AND OUTPUT OF STRUCTURED ARRAYS**

*1. Save into a file*

In [60]:
np.savetxt('population_table.csv',
          population_table,
          fmt = "%s;%d;%d;%d",
          delimiter = ";")

*2. read the file created*

In [68]:
dt = np.dtype([('Country', 'S20'),
               ('Density', 'i4'),
               ('Area', 'i4'), ('Population','i4')])

x = np.genfromtxt("population_table.csv", dtype = dt,
               delimiter = ";")
print(x['Country'][2:5])

[b"b'United Kingdom'" b"b'Germany'" b"b'Liechtensien'"]


In [76]:
dt = np.dtype([('Country', 'S20'),
               ('Density', 'i4'),
               ('Area', 'i4'), ('Population','i4')])

x = np.loadtxt("population_table.csv", dtype = dt,
               converters = {0: lambda x: x.decode('utf-8')},
               delimiter = ";")
d = x['Country'][5]
s = x['Area'][5]
print(type(d))
print(type(s))
print(s + 32)
print(x['Country'][2:5])

<class 'numpy.bytes_'>
<class 'numpy.int32'>
301262
[b"b'United Kingdom'" b"b'Germany'" b"b'Liechtensien'"]


**EXERCISE**

1.  Define a structured array with two columns. The first column contains the product ID, which can
 be defined as an int32. The second column shall contain the price for the product. How can you
 print out the column with the product IDs, the first row and the price for the third article of this
 structured array?

In [87]:
import numpy as np

art_type = np.dtype([('product ID', 'i4'),('price', np.float64)])

articles = np.array([
    (1145878, 100.75),
    (1145879, 150.50),
    (1145880, 50.150), 
    (1145881, 90.87),
    (1145882, 154.64)], dtype = art_type)
print('The products ID are :', articles['product ID'])
print('the first row is :', articles[0])
print('The price for the third article is :', articles['price'][2])

The products ID are : [1145878 1145879 1145880 1145881 1145882]
the first row is : (1145878, 100.75)
The price for the third article is : 50.15


2. Figure out a data type definition for time records with entries for hours, minutes and seconds.

In [90]:
import numpy as np

time_type = np.dtype([('hours', int),
               ('minutes', int),
               ('seconds', int)])