In [1]:
print(4+2)
print('I am a ' + 'woman')

6
I am a woman


The operator sign "+" can be used for the addition of numerical values and the concatenation of strings. We say that this operator is overloaded.
 
The operator signs are *overloaded* in Numpy as well, so that they can be used in a "natural" way. **We can, for example, add a scalar to an ndarray, i.e. the scalar will be added to every component**. The same is possible for subtraction, division, multiplication and even for applying functions, like sine, cosine and so on, to an array.

In [2]:
import numpy as np

lst = [1, 4.1, 5.3, 1.6, 8.6, 9.2, 6.7, 7.4]
v = np.array(lst)
v = v+2

print(v)

[ 3.   6.1  7.3  3.6 10.6 11.2  8.7  9.4]


In [3]:
print(v - 1.5)

[1.5 4.6 5.8 2.1 9.1 9.7 7.2 7.9]


In [4]:
print(v * 4)

[12.  24.4 29.2 14.4 42.4 44.8 34.8 37.6]


In [5]:
print(v/2)

[1.5  3.05 3.65 1.8  5.3  5.6  4.35 4.7 ]


In [6]:
print(v**2)

[  9.    37.21  53.29  12.96 112.36 125.44  75.69  88.36]


In [7]:
print(np.sqrt(v))

[1.73205081 2.46981781 2.70185122 1.8973666  3.25576412 3.34664011
 2.94957624 3.06594194]


As we say it before, operators on a ndarray applies to all element in de array.

To have the same result with a list, we shamm use the list comprehension technique as shown below :

In [12]:
import math

lst = [1, 4.1, 5.3, 1.6, 8.6, 9.2, 6.7, 7.4]

res = [val+2 for val in lst]
res2 = [val-1.5 for val in res]
res3 = [val*4 for val in res]
res4 = [val/2 for val in res]
res5 = [val**2 for val in res]
res6 = [math.sqrt(val) for val in res]
print(res)
print(res2)
print(res3)
print(res4)
print(res5)
print(res6)

[3, 6.1, 7.3, 3.6, 10.6, 11.2, 8.7, 9.4]
[1.5, 4.6, 5.8, 2.1, 9.1, 9.7, 7.199999999999999, 7.9]
[12, 24.4, 29.2, 14.4, 42.4, 44.8, 34.8, 37.6]
[1.5, 3.05, 3.65, 1.8, 5.3, 5.6, 4.35, 4.7]
[9, 37.209999999999994, 53.29, 12.96, 112.36, 125.43999999999998, 75.68999999999998, 88.36000000000001]
[1.7320508075688772, 2.4698178070456938, 2.701851217221259, 1.8973665961010275, 3.255764119219941, 3.3466401061363023, 2.949576240750525, 3.0659419433511785]


In [14]:
import numpy as np

lst = [1.0, 4.1, 5.3, 1.6, 8.6, 9.2, 6.7, 7.4, 2.8]
v = np.array(lst)
v = v.reshape(3,3)
print(v)

[[1.  4.1 5.3]
 [1.6 8.6 9.2]
 [6.7 7.4 2.8]]


In [16]:
print("Addition between scalar an array ")
print(v + 2)
print("Substraction between scalar an array ")
print(v - 1.5)
print("Multiplication between scalar an array ")
print(v * 4)
print("Division between scalar an array ")
print(v/2)
print("Exponentiation between scalar an array ")
print(v**2)
print("Square-root between scalar an array ")
print(np.sqrt(v))

Addition between scalar an array 
[[ 3.   6.1  7.3]
 [ 3.6 10.6 11.2]
 [ 8.7  9.4  4.8]]
Substraction between scalar an array 
[[-0.5  2.6  3.8]
 [ 0.1  7.1  7.7]
 [ 5.2  5.9  1.3]]
Multiplication between scalar an array 
[[ 4.  16.4 21.2]
 [ 6.4 34.4 36.8]
 [26.8 29.6 11.2]]
Division between scalar an array 
[[0.5  2.05 2.65]
 [0.8  4.3  4.6 ]
 [3.35 3.7  1.4 ]]
Exponentiation between scalar an array 
[[ 1.   16.81 28.09]
 [ 2.56 73.96 84.64]
 [44.89 54.76  7.84]]
Square-root between scalar an array 
[[1.         2.02484567 2.30217289]
 [1.26491106 2.93257566 3.03315018]
 [2.58843582 2.7202941  1.67332005]]


**ARITHMETIC OPERATIONS WITH TWO ARRAYS**

If we use another array instead of a scalar, the elements of both arrays will be component-wise combined

In [19]:
import numpy as np

A = np.array([ [11,12,13], [21,22,23], [31,32,33] ])
B = np.ones((3,3))

print("Addition of A AND B")
print(A+B)
print("Multiplication of A and B")
print(A*(B+1))

Addition of A AND B
[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]
Multiplication of A and B
[[22. 24. 26.]
 [42. 44. 46.]
 [62. 64. 66.]]


Don't mistake A*B for a matrix multiplication

For matrix multiplication, use the **dot product** as shown below :

In [20]:
np.dot(A,B)

array([[36., 36., 36.],
       [66., 66., 66.],
       [96., 96., 96.]])

In two dimensional use, we have :

In [22]:
A = np.array([ [1, 2, 3],
               [3, 2, 1] ])
B = np.array([ [2, 3, 4,-2],
               [1,-1, 2, 3],
               [1, 2, 3, 0] ])
# es muss gelten:
print(A.shape[-1] == B.shape[-2], A.shape[1]) #I have to 
                                            #remember this line

print(A.shape[1]== B.shape[0], A.shape[1])
print(np.dot(A, B))

True 3
True 3
[[ 7  7 17  4]
 [ 9  9 19  0]]


**THE DOT PRODUCT IN THE 3-DIMENSIONAL CASE**

I shall learn it after :)

**MATRICES VS. TWO-DIMENSIONAL ARRAYS**

There are "real" matrices in Numpy. They are a subset of the two-dimensional arrays. The main difference shows, if you multiply two two-dimensional arrays or two matrices. **We get real matrix multiplication by multiplying two matrices**, but the two-dimensional arrays will be only multiplied component-wise

In [23]:
import numpy as np
 
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1,-2,-3] ])
 
print("Multiplication between two 2darrays")
print(A * B)

#Matrix transformation
MA = np.mat(A)
MB = np.mat(B)

print("Multiplication between two matrix")
print(MA * MB)

Multiplication between two 2darrays
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Multiplication between two matrix
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


**COMPARISON OPERATORS**

In [24]:
import numpy as np
 
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([ [11, 102, 13], [201, 22, 203], [31, 32, 303] ])
 
A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

When we compare two arrays, we don't get a simple True or False as a return value. The comparisons are performed elementswise. This means that we get a Boolean array as a return value. But it is possible to compare complete arrays for equality as well. We use **array_equal** for this purpose :

In [25]:
print(np.array_equal(A, B))
print(np.array_equal(A, A))

False
True


**LOGICAL OPERATORS**

In [26]:
import numpy as np

a = np.array([ [True, True], [False, False]])
b = np.array([ [True, False], [True, False]])
 
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[[ True  True]
 [ True False]]
[[ True False]
 [False False]]


In [27]:
import numpy as np

a = np.array([ [1, 1], [0, 0]])
b = np.array([ [1, 0], [1, 0]])
 
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[[ True  True]
 [ True False]]
[[ True False]
 [False False]]


In [32]:
a = np.array([ [1, 2], [-0.15, 0.25]])
b = np.array([ [4, 0], [11, 0]])
 
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[[ True  True]
 [ True  True]]
[[ True False]
 [ True False]]


**BROADCASTING**

In [33]:
import numpy as np

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
 
print("Multiplication with broadcasting: ")
print(A * B)
print("... and now addition with broadcasting: ")
print(A + B)

Multiplication with broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


We have a smaller array and a larger array, and we transform or apply the smaller array multiple times to perform some operation on the larger array.  The smaller array is **"broadcasted"** in a way that it has the same shape as the larger array.

In [34]:
B = np.array([1, 2, 3])
B[:, np.newaxis]

array([[1],
       [2],
       [3]])

Here, we turn a row vector into a column vector.

Now we are capable of doing the multipliplication using broadcasting:

In [35]:
A * B[:, np.newaxis]

array([[11, 12, 13],
       [42, 44, 46],
       [93, 96, 99]])

In [90]:
B = np.array([1,2,3])

print("B is construed like a 3*3 array like this ")
print(np.array([B,] * 3))

print("...............or like this ")

B = B[np.newaxis,:]
print(np.concatenate((B,B,B)))

B is construed like a 3*3 array like this 
[[1 2 3]
 [1 2 3]
 [1 2 3]]
...............or like this 
[[1 2 3]
 [1 2 3]
 [1 2 3]]
C is the transpose of B 
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [92]:
B = np.array([1,2,3])


C = np.array([B,] * 3).transpose()
print("C is the transpose of B ")
print(C)

C is the transpose of B 
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [60]:
B = np.array([1,2,3])
print(np.concatenate((B,B)))
B.ndim

[1 2 3 1 2 3]


1

In [63]:
B = np.array([1,2,3])
B = B[:, np.newaxis]
B = np.concatenate((B,B))

print(B)
B.ndim

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]


2

In [74]:
#With broadcasting
A = np.array([10, 20, 30])
B = np.array([1, 2, 3])

A[:, np.newaxis]*B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [81]:
#Without broadcasting
A = np.array([10, 20, 30])
B = np.array([1, 2, 3])

A = np.transpose([A,]*3)
#A = np.array([A,]*3).transpose()
B = B[np.newaxis,:]
B = np.concatenate((B,B,B))

A*B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [83]:
#Without broadcasting

import numpy as np

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
 
B = B[np.newaxis,:]
B = np.concatenate((B,B,B))
print("Multiplication without broadcasting: ")
print(A * B)
print("... and now addition with broadcasting: ")
print(A + B)

Multiplication without broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


In [102]:
dist2barcelona = [0, 1498, 1063, 1968,
 1498, 1758, 1469, 1472, 2230,
 2391, 1138, 505, 725, 3007, 1055,
 833, 1354, 857, 2813,
 2277, 1347, 1862]
dists = np.array(dist2barcelona[:12])
#print(dists)     # row vector
#print(dists[:, np.newaxis])    # column vector
print(np.abs(dists-dists[:, np.newaxis]))

[[   0 1498 1063 1968 1498 1758 1469 1472 2230 2391 1138  505]
 [1498    0  435  470    0  260   29   26  732  893  360  993]
 [1063  435    0  905  435  695  406  409 1167 1328   75  558]
 [1968  470  905    0  470  210  499  496  262  423  830 1463]
 [1498    0  435  470    0  260   29   26  732  893  360  993]
 [1758  260  695  210  260    0  289  286  472  633  620 1253]
 [1469   29  406  499   29  289    0    3  761  922  331  964]
 [1472   26  409  496   26  286    3    0  758  919  334  967]
 [2230  732 1167  262  732  472  761  758    0  161 1092 1725]
 [2391  893 1328  423  893  633  922  919  161    0 1253 1886]
 [1138  360   75  830  360  620  331  334 1092 1253    0  633]
 [ 505  993  558 1463  993 1253  964  967 1725 1886  633    0]]


Here is a **distance matrix** whose calculation requires broadcasting

**3-DIMENSIONAL BROADCASTING**

I shall learn it after