In [1]:
import numpy as np

In [4]:
A = np.array([[11, 12, 13],
              [21, 22, 23],
              [31, 32, 33],
              [41, 42, 43]])
print(A.flatten())
print(A.ravel())

[11 12 13 21 22 23 31 32 33 41 42 43]
[11 12 13 21 22 23 31 32 33 41 42 43]


In [5]:
B = A.ravel()
print(B.reshape(2,2,3))

[[[11 12 13]
  [21 22 23]]

 [[31 32 33]
  [41 42 43]]]


In [7]:
x = np.array([11,22])
y = np.array([18,7,6])
z = np.array([1,3,5])

c = np.concatenate((x,y,z))
print(c)

[11 22 18  7  6  1  3  5]


If we are concatenating multidimensional arrays, we can concatenate the arrays according to axis. **Arrays must
 have the same shape to be concatenated with concatenate().**

In [9]:
x = np.array(range(24))
x = x.reshape((3,4,2))
y = np.array(range(100,124))
y = y.reshape((3,4,2))


z = np.concatenate((x,y))
print(z.shape)
print(z)

(6, 4, 2)
[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]]

 [[100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[116 117]
  [118 119]
  [120 121]
  [122 123]]]


In the case of multidimensional arrays, we can
 arrange them according to the axis. The default value is axis = 0

In [10]:
z = np.concatenate((x,y), axis = 1)
print(z.shape)
print(z)

(3, 8, 2)
[[[  0   1]
  [  2   3]
  [  4   5]
  [  6   7]
  [100 101]
  [102 103]
  [104 105]
  [106 107]]

 [[  8   9]
  [ 10  11]
  [ 12  13]
  [ 14  15]
  [108 109]
  [110 111]
  [112 113]
  [114 115]]

 [[ 16  17]
  [ 18  19]
  [ 20  21]
  [ 22  23]
  [116 117]
  [118 119]
  [120 121]
  [122 123]]]


In [11]:
z = np.concatenate((x,y), axis = 2)
print(z.shape)
print(z)

(3, 4, 4)
[[[  0   1 100 101]
  [  2   3 102 103]
  [  4   5 104 105]
  [  6   7 106 107]]

 [[  8   9 108 109]
  [ 10  11 110 111]
  [ 12  13 112 113]
  [ 14  15 114 115]]

 [[ 16  17 116 117]
  [ 18  19 118 119]
  [ 20  21 120 121]
  [ 22  23 122 123]]]


**ADDING NEW DIMENSIONS**

New dimensions can be added to an array by using slicing and np.newaxis

In [18]:
x = np.array([2,5,18,14,4])
y = x[:, np.newaxis]

print(x.ndim)
print(y.ndim)
print(y)

1
2
[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


In [17]:
y = y[:, np.newaxis]
print(y.ndim)
print(y)

3
[[[ 2]]

 [[ 5]]

 [[18]]

 [[14]]

 [[ 4]]]


**VECTOR STACKING**

In [19]:
A = np.array([3, 4, 5])
B = np.array([1,9,0])

print(np.row_stack((A, B)))
print(np.column_stack((A, B)))
np.shape(A)

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


(3,)

In [20]:
A = np.array([[3, 4, 5],
              [1, 9, 0],
              [4, 6, 8]])
np.column_stack((A, A, A))

array([[3, 4, 5, 3, 4, 5, 3, 4, 5],
       [1, 9, 0, 1, 9, 0, 1, 9, 0],
       [4, 6, 8, 4, 6, 8, 4, 6, 8]])

In [21]:
np.row_stack((A, A, A))

array([[3, 4, 5],
       [1, 9, 0],
       [4, 6, 8],
       [3, 4, 5],
       [1, 9, 0],
       [4, 6, 8],
       [3, 4, 5],
       [1, 9, 0],
       [4, 6, 8]])

In [22]:
np.dstack((A, A, A))

array([[[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]],

       [[1, 1, 1],
        [9, 9, 9],
        [0, 0, 0]],

       [[4, 4, 4],
        [6, 6, 6],
        [8, 8, 8]]])

In [27]:
B = A[0]
print(np.column_stack((B,B,B)))
print(np.row_stack((B,B,B)))

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[[3 4 5]
 [3 4 5]
 [3 4 5]]


**REPEATING PATTERNS, THE "TILE" METHOD**

*tile(A, reps)*

 'reps' is usually a tuple (or list) which defines the number of repetitions along the corresponding axis /
 directions. if we set reps to (3, 4) for example, A will be repeated 3 times for the "rows" and 4 times in the
 direction of the columna

In [23]:
x = np.array([ 3.4])
y = np.tile(x, (5,))
print(y)

y = np.tile(x, 5)
print(y)

[3.4 3.4 3.4 3.4 3.4]
[3.4 3.4 3.4 3.4 3.4]


In [24]:
x = np.array([ [1, 2], [3, 4]])
np.tile(x, (3,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])