In [1]:
import numpy as np

**I. THE RANDOM MODULE**

In [24]:
import random

print(random.random())

0.5736031272912688


We will show an alternative and **secure approach in the following example**, in which we will use the class
 SystemRandom of the random module below: 

In [26]:
from random import SystemRandom

crypto = SystemRandom()
print(crypto.random())

0.06505812831491409


The random method of the SystemRandom class generates a float number in the range from 0.0 (included) to
 1.0 (not included)

**GENERATE A LIST OF RANDOM NUMBERS**

*1. Using pure Python module : random*

In [25]:
import random

def random_list(n, secure = True):
    random_floats = []
    if secure:
        crypto = random.SystemRandom()
        random_float = crypto.random()
    else:
        random_float = random.random()
    for _ in range(n):
        random_floats.append(random_float)
    return random_floats

print(random_list(10, secure = False))

[0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087, 0.3820621171153087]


*2. Using the random package of the numpy module.*

In [8]:
print(np.random.random(10))

[0.43643155 0.49606872 0.6276591  0.30965515 0.96143601 0.87360188
 0.29577439 0.72982529 0.67729028 0.84130833]


The fastest and most efficient way will be using the random package of the numpy module like shown up

**RANDOM NUMBERS SATISFYING SUM-TO-ONE CONDITION**

In [13]:
list_of_random_floats = np.random.random(100)
sum_of_values = list_of_random_floats.sum()
print(sum_of_values)

normalized_values = list_of_random_floats / sum_of_values
print(normalized_values.sum())

49.348365149555754
1.0


**GENERATING RANDOM STRINGS OR PASSWORDS WITH PYTHON**

I will learn it after

**RANDOM INTEGER NUMBERS**

*numpy.random.randint(low, high=None, size=None)*

This function returns random integers from 'low' (inclusive) to 'high' (exclusive)

In [14]:
import random

outcome = random.randint(1,6)
print(outcome)

A = [random.randint(1, 6) for _ in range(10)]
print(A)

5
[3, 6, 5, 3, 5, 3, 2, 5, 2, 3]


In [16]:
outcome = np.random.randint(1, 7, size=10)
print(outcome)

[4 4 4 5 5 6 2 3 4 1]


numpy.random.randint(low, high=None, size=None)

In [18]:
print(np.random.randint(1, 7))
print(np.random.randint(1, 7, size=1))
print(np.random.randint(1, 7, size=10))
print(np.random.randint(1, 7, size=(10,))) # the same as the 
                                           # previous one
print(np.random.randint(1, 7, size=(5, 4)))

5
[3]
[4 5 4 3 5 5 3 1 3 3]
[3 3 4 3 3 5 4 1 5 6]
[[1 2 5 3]
 [5 2 2 3]
 [2 1 6 3]
 [4 4 5 4]
 [6 6 6 3]]


**RANDOM CHOICES WITH PYTHON**

In [29]:
from random import choice

possible_destinations = ["Berlin", "Hamburg", "Munich",
                         "Amsterdam", "London", "Paris",
                         "Zurich", "Heidelberg", "Strasbourg",
                         "Augsburg", "Milan", "Rome"]
print(choice(possible_destinations))

Berlin


In [30]:
from numpy.random import choice

print(choice(possible_destinations))
 
x1 = choice(possible_destinations, size=3)
print(x1)

x2 = choice(possible_destinations, size=(3, 4))
print(x2)

Paris
['Augsburg' 'Milan' 'Munich']
[['Amsterdam' 'Munich' 'Heidelberg' 'Hamburg']
 ['Amsterdam' 'Berlin' 'Zurich' 'Hamburg']
 ['Strasbourg' 'Strasbourg' 'Heidelberg' 'Augsburg']]


In [31]:
print(choice(possible_destinations, size=(3, 4), replace=False))

[['Amsterdam' 'Zurich' 'Paris' 'Heidelberg']
 ['Strasbourg' 'Milan' 'Augsburg' 'Berlin']
 ['London' 'Rome' 'Munich' 'Hamburg']]


We can prevent multiples occurences by setting the
 optional parameter "replace" to "False"

**RANDOM SAMPLES WITH PYTHON**

The module numpy.random contains a function random_sample, which returns random floats in the half open
 interval [0.0, 1.0)

In [34]:
x = np.random.random_sample((3,4))
print(x)

[[0.37620859 0.13594931 0.04766134 0.7537209 ]
 [0.23459178 0.45778455 0.32544858 0.07289158]
 [0.40852604 0.03121217 0.9839056  0.77751493]]


In [37]:
from numpy.random import random_sample

x = random_sample((3,))
print(x)

[0.64225507 0.0531061  0.66519788]


In [39]:
a =-3.4
b = 5.9
 
A = (b - a) * np.random.random_sample((2,3)) + a
print(A)

[[-2.47753993  1.02269584  4.62562787]
 [ 0.90079747 -2.87651911  5.03199063]]


You can also generate arrays with values from an arbitrary interval [a, b), where a has to be less than b. It can be done like shown up.

*The standard module random of Python has a more general function "sample", which produces samples from a
 population*
 
The syntax of sample:
 *sample(population, k)*

In [40]:
#We want to choose a sample within a range of integers, you can - or better you should - use range as the argument for the population.
import random

print(random.sample(range(1, 50), 6))

[35, 28, 1, 9, 21, 46]


**II. WEIGHTED PROBABILITIES**

*1. WEIGHTED RANDOM CHOICES*

In [41]:
import numpy as np

In [42]:
import random
from random import random
 
def weighted_choice(objects, weights):
    weights = np.array(weights, dtype=np.float64)
    sum_of_weights = weights.sum()
    # standardization:
    np.multiply(weights, 1 / sum_of_weights, weights)
    weights = weights.cumsum()
    x = random()
    for i in range(len(weights)):
        if x < weights[i]:
            return objects[i]

In [44]:
from collections import Counter

faces_of_die = [1, 2, 3, 4, 5, 6]
weights = [1/12, 1/6, 1/6, 1/6, 1/6, 3/12]
outcomes = []
n = 10000
 
for _ in range(n):
    outcomes.append(weighted_choice(faces_of_die, weights))
c = Counter(outcomes)
print(c)
for key in c:
    c[key] = c[key] / n

print(sorted(c.values()), sum(c.values()))

Counter({6: 2424, 2: 1714, 3: 1686, 5: 1677, 4: 1670, 1: 829})
[0.0829, 0.167, 0.1677, 0.1686, 0.1714, 0.2424] 1.0


We define a list of cities and a list with their corresponding populations. The probability of a city to be chosen should be according to their size:

In [48]:
cities = ["Frankfurt", "Stuttgart", "Freiburg", "München", "Zürich", "Hamburg"]
populations = [736000, 628000, 228000, 1450000, 409241, 1841179]
total = sum(populations)
weights = [ round(pop / total, 2) for pop in populations]
print(weights)
 
for i in range(10):
    print(weighted_choice(cities, populations))

[0.14, 0.12, 0.04, 0.27, 0.08, 0.35]
Hamburg
Frankfurt
München
Zürich
Stuttgart
Hamburg
München
Hamburg
München
Stuttgart


*WEIGHTED SAMPLE*

In [52]:
def weighted_sample(population, weights, k):
    """
    This function draws a random sample (without repeats)
    of length k     from the sequence 'population' according
    to the list of weights
    """
    sample = set()
    population = list(population)
    weights = list(weights)
    while len(sample) < k:
        choice = weighted_choice(population, weights)
        sample.add(choice)
        index = population.index(choice)
        weights.pop(index)
        population.remove(choice)
        weights = [ x / sum(weights) for x in weights]
    return list(sample)

In [53]:
candies = ["red", "green", "blue", "yellow", "black", "white", "pink", "orange"]
weights = [ 1/24, 1/6, 1/6, 1/12, 1/12, 1/24, 1/8, 7/24]
for i in range(10):
    print(weighted_sample(candies, weights, 3))

['black', 'blue', 'orange']
['black', 'green', 'orange']
['green', 'blue', 'orange']
['green', 'blue', 'red']
['green', 'orange', 'red']
['green', 'orange', 'red']
['pink', 'yellow', 'red']
['pink', 'blue', 'orange']
['black', 'green', 'blue']
['black', 'green', 'pink']


*2. WEIGHTED RANDOM CHOICE WITH NUMPY*

choice(a, size=None, replace=True, p=None)

In [49]:
from numpy.random import choice

professions = ["scientist", "philosopher", "engineer", "priest", "programmer"]

probabilities = [0.2, 0.05, 0.3, 0.15, 0.3]

choice(professions, p=probabilities)

'programmer'

In [50]:
choice(professions, size = 2, p = probabilities)

array(['engineer', 'scientist'], dtype='<U11')

In [51]:
programming_languages = ["Java", "C", "Python", "C++"]
weights = np.array([16, 15.2, 10, 6.1])
 
# normalization
weights /= sum(weights)
print(weights)
for i in range(10):
    print(choice(programming_languages, p=weights))

[0.33826638 0.32135307 0.21141649 0.12896406]
Java
Python
C
Java
Java
C
C
Python
Java
C


*Let us redo the previous example by substituting weighted_sampe with a call of np.random.choice:*

In [55]:
candies = ["red", "green", "blue", "yellow", "black", "white", "pink", "orange"]
weights = [ 1/24, 1/6, 1/6, 1/12, 1/12, 1/24, 1/8, 7/24]

for i in range (4):
    print(choice(candies, p = weights, size=3))

['blue' 'orange' 'orange']
['orange' 'blue' 'blue']
['orange' 'red' 'orange']
['blue' 'black' 'pink']


In [56]:
candies = ["red", "green", "blue", "yellow", "black", "white", "pink", "orange"]
weights = [ 1/24, 1/6, 1/6, 1/12, 1/12, 1/24, 1/8, 7/24]

for i in range (4):
    print(choice(candies, p = weights, size=3, replace = False))

['yellow' 'blue' 'orange']
['yellow' 'orange' 'black']
['pink' 'orange' 'green']
['green' 'yellow' 'black']
