In [9]:
import numpy as np

In [10]:
A = np.array([4, 7, 3, 4, 2, 8])
 
print(A == 4)

[ True False False  True False False]


In [11]:
print(A<5)

[ True False  True  True  True False]


In [12]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])
print(B>=42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


In [24]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])
C = B<42
#print(C)
print(C.astype(int))
print(C.astype(np.int8))

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 1]]
[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 1]]


*FANCY INDEXING*

In [33]:
C = np.array(np.random.choice(range(100,150), size = 8))
A = np.array(np.random.randint(1, 10, size = 8))
print(C)
print(A)


R = C[A<=5]
print(R)

[140 129 140 135 128 129 119 131]
[8 3 5 8 8 9 8 4]
[129 140 131]


The new array R contains all the elements of C where the corresponding value of (A<=5) is
 True.

In [34]:
C[[0, 2, 3, 1, 4, 1]]

array([140, 140, 135, 129, 128, 129])

we can index with an integer array. Indices can appear in every order and multiple times!

**EXERCISE**

In [45]:
x = np.array([3,4,6,10,24,89,45,43,46,99,100])

D3D = x[x%3!=0]
print("Elements of x not divisible by 3: " + str(D3D))

D5D = x[x%5==0]
print("Elements of x divisible by 5: " + str(D5D))

D3D5 = x[(x%3==0)&(x%5==0)]
print("Elements of x divisible by 3 and 5: " + str(D3D5))

Elements of x not divisible by 3: [  4  10  89  43  46 100]
Elements of x divisible by 5: [ 10  45 100]
Elements of x divisible by 3 and 5: [45]


In [48]:
x[x%3==0] = 42
print("""New values of A after setting the elements of A, which are divisible by 3, to 42:""")
print(x)

New values of A after setting the elements of A, which are divisible by 3, to 42:
[ 42   4  42  10  42  89  42  43  46  42 100]


**NONZERO AND WHERE**

For an ndarray a both numpy.nonzero(a) and a.nonzero() return the indices of the elements of a that are non
zero

In [49]:
a = np.array([[0, 2, 3, 0, 1],
              [1, 0, 0, 7, 0],
              [5, 0, 0, 1, 0]])
 
print(a.nonzero())

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 4, 0, 3, 0, 3], dtype=int64))


If you want to group the indices by element, you can use transpose:

*np.transpose(np.nonzero(a))*

In [68]:
print(np.transpose(a.nonzero()))
print(np.transpose(np.nonzero(a)))

[[0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [2 0]
 [2 3]]
[[0 1]
 [0 2]
 [0 4]
 [1 0]
 [1 3]
 [2 0]
 [2 3]]


 The corresponding non-zero values can be retrieved with:
 
 *a[a.nonzero()]* or *a[numpy.nonzero(a)]*

In [51]:
a[a.nonzero()]

array([2, 3, 1, 1, 7, 5, 1])

In [52]:
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])
 
print(B >= 42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


In [53]:
np.transpose((B >= 42).nonzero())

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1]], dtype=int64)

In [54]:
B[(B >= 42).nonzero()]

array([42, 56, 89, 65, 99, 88, 42, 55, 42])

**EXERCISE**

Calculate the prime numbers between 0 and 100 by using a Boolean array.

In [55]:
import numpy as np
 
is_prime = np.ones((100,), dtype=bool)
 
# Cross out 0 and 1 which are not primes:
is_prime[:2] = 0

# cross out its higher multiples (sieve of Eratosthenes):
nmax = int(np.sqrt(len(is_prime)))
for i in range(2, nmax):
    is_prime[2*i::i] = False

print(np.nonzero(is_prime))

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64),)


In [59]:
import numpy as np
 
is_prime = np.ones((100,), dtype=bool)

# Cross out 0 and 1 which are not primes:
is_prime[:2] = 0

# cross out its higher multiples (sieve of Eratosthenes):
nmax = int(np.sqrt(len(is_prime)))
for i in range(2, nmax):
    is_prime[i*i::i] = False     #changes from the precedent program occurs there

print(np.nonzero(is_prime))

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64),)


**FLATNONZERO AND COUNT_NONZERO**

- *flatnonzero* :
 Return indices that are non-zero in the flattened version of the input
 array.
 
- *count_nonzero* :
 Counts the number of non-zero elements in the input array.

In [65]:
a = np.array([[0, 2, 3, 0, 1],
              [1, 0, 0, 7, 0],
              [5, 0, 0, 1, 0]])
 
print(np.flatnonzero(a))

[ 1  2  4  5  8 10 13]


In [63]:
print(np.count_nonzero(a))

7
