**SCALAR PRODUCT / DOT PRODUCT**

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
y = np.array([-7, 8, 9])
np.dot(x, y)

36

In [4]:
dot = np.dot(x ,y)
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle = dot / x_modulus / y_modulus # cosine of angle between x and y
angle = np.arccos(cos_angle)
angle

0.808233789010825

In [5]:
angle * 360 / 2 / np.pi # angle in degrees

46.308384970187326

**MATRIX PRODUCT**

In [8]:
NumPersons = np.array([[100, 175, 210],
                        [90, 160, 150],
                        [200, 50, 100],
                        [120, 0, 310]])
Price_per_100_g = np.array([2.98, 3.90, 1.99])
Price_in_Cent = np.dot(NumPersons,Price_per_100_g)
Price_in_Euro = Price_in_Cent / 100
Price_in_Euro

array([13.984, 11.907,  9.9  ,  9.745])

**CROSS PRODUCT**

The cross product of two vectors a and b is denoted by a × b

In [9]:
x = np.array([0, 0, 1])
y = np.array([0, 1, 0])

np.cross(x, y)

array([-1,  0,  0])

In [10]:
np.cross(y, x)

array([1, 0, 0])