In [1]:
import numpy as np

**SAVING TEXTFILES WITH SAVETXT**

*savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')*

In [3]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], np.int32)
 
y = np.savetxt("test.txt", x)
z = np.savetxt("test2.txt", x, fmt="%2.3f", delimiter=",")
w = np.savetxt("test3.txt", x, fmt="%04d", delimiter=" :-) ")

**LOADING TEXTFILES WITH LOADTXT**

In [4]:
a = np.loadtxt("test.txt")
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
a = np.loadtxt("test2.txt", delimiter=",")
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [12]:
a = np.loadtxt("test2.txt", delimiter=",", usecols=(0,2))
print(a)

[[1. 3.]
 [4. 6.]
 [7. 9.]]


*We will read in our next example the file "times_and_temperatures.txt", which we have created in our chapter on Generators of our Python tutorial. Every line contains a time in the format "hh::mm::ss" and random
 temperatures between 10.0 and 25.0 degrees. We have to convert the time string into float numbers. The time will be in minutes with seconds in the hundred.*

In [30]:
def time2float_minutes(time):
    if type(time) == bytes:
        time = time.decode()
    t = time.split(":")
    minutes = float(t[0])*60 + float(t[1]) + float(t[2]) * 0.05 / 3
    return minutes

In [31]:
for t in ["06:00:10", "06:27:45", "12:59:59"]:
    print(time2float_minutes(t))

360.1666666666667
387.75
779.9833333333333


We use **";"** as delimiter instead of whitespace and change the filename into *times_temperatures*.

In [78]:
from timerange import trange
import random

fh = open("times_temperatures.txt", "w")

for time in trange((6, 0, 0), (23, 0, 0), (0, 1, 30) ):
    random_number = random.randint(100, 250) / 10
    lst = time + (random_number,)
    output = "{:02d}:{:02d}:{:02d};{:4.1f}\n".format(*lst)
    fh.write(output)

In [87]:
y = np.loadtxt("times_temperatures.txt", delimiter = ";", converters={ 0: time2float_minutes}, usecols=(0,1))
print(y)

[[ 360.    11.1]
 [ 361.5   22.4]
 [ 363.    15. ]
 ...
 [1375.5   23. ]
 [1377.    23.2]
 [1378.5   22.2]]


In [88]:
y = np.loadtxt("times_temperatures.txt", delimiter = ";", converters={ 0: time2float_minutes}, usecols=(1))
print(y[0:10])

[11.1 22.4 15.  21.6 16.4 15.9 16.9 21.5 10.6 22.1]


We work with the same example as in the book

In [80]:
y = np.loadtxt("times_and_temperatures.txt", converters={ 0: time2float_minutes})
print(y)

[[ 360.    19.8]
 [ 361.5   23.3]
 [ 363.    16.7]
 ...
 [1375.5   20.4]
 [1377.    20.8]
 [1378.5   22.1]]


In [81]:
y = np.loadtxt("times_and_temperatures.txt", converters={ 0: time2float_minutes}, usecols=(0))
print(y[::50])

[ 360.  435.  510.  585.  660.  735.  810.  885.  960. 1035. 1110. 1185.
 1260. 1335.]


In [82]:
y = np.loadtxt("times_and_temperatures.txt", usecols=(0), converters={ 0: time2float_minutes})
print(y[0:300:50])

[360. 435. 510. 585. 660. 735.]


In [83]:
a = np.savetxt("test4.txt", y, fmt = "%2.1f", delimiter=",")

In [84]:
b = np.loadtxt("test4.txt", delimiter=",", usecols=(0))
print(b.shape)

(680,)
